### ISSUE TITLE
How much GPU do you consume?

### ISSUE THREAD

**Issue by ilikeokoge** [zheshiyige/Learning-Diverse-Stochastic-Human-Action-Generators-by-Learning-Smooth-Latent-Transitions#1]
Thank you for the great code base!
I try to do STEP1 and STEP2.
I seem to be consuming very few GPUs(500MB).
How much GPU do you consume in your experience?

**Comment by zheshiyige** [comment]
less than 2G if I remember correctly.

Best Regards,
Zhenyi

**Comment by ilikeokoge** [comment]
Thanks for the quick reply!
It's almost the same as me.
