### ISSUE TITLE
How did you calculate the MMD and Accuracy?

### ISSUE THREAD

**Issue by ilikeokoge** [zheshiyige/Learning-Diverse-Stochastic-Human-Action-Generators-by-Learning-Smooth-Latent-Transitions#2]
It does not appear to contain the code to calculate the MMD and Accracy in paper's Table1,2. 
Do you plan to share that code?

**Comment by joey-wang123** [comment]
For the MMD, as it needs to use 1000 sequences for each class, for my destop with power less than 500W, it will shut down immediately.  So, we only test it on a high performance server. We will try to improve its implementation afterwards for usual computer. For the accuracy, it depends on another code base, we haven't cleaned it yet, we will try to clean it later as we currently work on another project.

**Comment by zheshiyige** [comment]
For the MMD, as it needs to use 1000 sequences for each class, for my destop with power less than 500W, it will shut down immediately. So, we only test it on a high performance server. We will try to improve its implementation afterwards for usual computer. For the accuracy, it depends on another code base, we haven't cleaned it yet, we will try to clean it later as we currently work on another project.

**Comment by ilikeokoge** [comment]
Thanks for the quick reply!
I see. I look forward to seeing the code.
